apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localSecretStore
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "./components/secrets/secret.json"
    - name: nestedSeparator
      value: ":"
    - name: multiValued
      value: "false"
