/*
 * Copyright 2025 The Dapr Authors
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
limitations under the License.
*/

package io.dapr.client.domain;

/**
 * Represents a function call within a tool call.
 */
public class ConversationToolCallsOfFunction {

  private final String name;
  private final String arguments;

  /**
   * Constructor.
   *
   * @param name the name of the function to call
   * @param arguments the arguments to call the function with, as generated by the model in JSON format
   */
  public ConversationToolCallsOfFunction(String name, String arguments) {
    this.name = name;
    this.arguments = arguments;
  }

  /**
   * Gets the name of the function to call.
   *
   * @return the function name
   */
  public String getName() {
    return name;
  }

  /**
   * Gets the arguments to call the function with, as generated by the model in JSON format.
   * Note that the model does not always generate valid JSON, and may hallucinate parameters
   * not defined by your function schema. Validate the arguments in your code before calling your function.
   *
   * @return the function arguments in JSON format
   */
  public String getArguments() {
    return arguments;
  }
}
